In [1]:
a={'1':10,'2':20}

In [2]:
print(a.items())

dict_items([('1', 10), ('2', 20)])


In [3]:
b=[a[x] for (x) in a]
print(b)

[10, 20]


In [4]:
for z in a:
    print(z)

1
2


In [5]:
def get_dict_value(x):
    return [x[key] for key in x]

In [6]:
get_dict_value(a)

[10, 20]

In [7]:
import torch
x=torch.rand(10)

In [8]:
torch.optim.SGD([x],lr=0.0)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.0
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [11]:
x=torch.randn(1,3)
print(x)
print(abs(x).mean())

tensor([[ 0.1306, -1.6080,  0.4438]])
tensor(0.7275)


In [12]:
torch.randn(x.shape)*0.1

tensor([[-0.0775, -0.1577,  0.0532]])

In [9]:
print(z)

2


In [10]:
z=torch.stack(z)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not str

In [11]:
print(z)

2


In [17]:
z=0

In [13]:
device='cuda:0'

In [14]:
x=torch.rand(2,3,device=device)

In [15]:
print(x)

tensor([[0.9063, 0.6041, 0.8709],
        [0.1802, 0.2863, 0.0569]], device='cuda:0')


In [16]:
torch.cat((x,torch.rand(2,3,device=device)),dim=0)

tensor([[0.9063, 0.6041, 0.8709],
        [0.1802, 0.2863, 0.0569],
        [0.5110, 0.3810, 0.0772],
        [0.1873, 0.7925, 0.5129]], device='cuda:0')

In [20]:
a=torch.range(start=0,end=9,dtype=int).to(device)

/home/dana/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


In [25]:
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')


In [29]:
print(a.repeat(5))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9], device='cuda:0')


In [19]:
z+=([torch.rand(3,2) for i in range(3)])

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [15]:
z

tensor([[[0.0218, 0.5408],
         [0.4797, 0.2115],
         [0.2291, 0.5883]],

        [[0.7556, 0.6585],
         [0.8088, 0.2401],
         [0.7925, 0.8790]],

        [[0.7584, 0.3880],
         [0.5304, 0.9809],
         [0.3396, 0.8625]]])

In [39]:
z.mean(dim=0)

tensor([[0.5397, 0.3704],
        [0.6379, 0.5089],
        [0.2797, 0.4445]])

In [43]:
torch.cat([z,torch.rand(3,2)])

RuntimeError: torch.cat(): Tensors must have same number of dimensions: got 3 and 2